import type { KnowledgeGoal } from '../../../shared/knowledge'
import { KNOWLEDGE_TODO_FILE } from '../../../shared/knowledge'

/** Frozen source endpoints and goals travel in the original Run, including all recovery prompts. */
export function knowledgeIntakePrompt(input: { fromCommit: string | null; toCommit: string;
  paths: readonly string[]; goals: readonly KnowledgeGoal[]; instruction: string }): string {
  return [
    'Curate the frozen raw input against Knowledge goals. First screen all raw changes with system_one and collect one todo list; then process that list into evidence-backed Wiki assets.',
    `Raw fromCommit: ${input.fromCommit ?? '(initial full snapshot)'}`,
    `Raw toCommit: ${input.toCommit}`,
    `Raw paths:\n${input.paths.map(path => `- ${path}`).join('\n')}`,
    `Frozen Knowledge goals:\n${JSON.stringify(input.goals, null, 2)}`,
    `Task-local progress file: ${KNOWLEDGE_TODO_FILE}. It is ignored by Git and must remain outside Wiki publication.`,
    `Phase 1 — screening:\n` +
    'Read each changed raw diff from fromCommit to toCommit; for an initial intake read every listed raw from the full frozen toCommit tree. Check git diff --name-status --no-renames to distinguish added and modified files: added lines in numstat do not mean a new file. Use git show <commit>:<raw-path> for current and prior context. For deleted raws read the diff and prior blob. Do not consume newer working-tree raw content.\n' +
    'Understand complete discussions before screening. Follow relevant preceding and subsequent messages in the frozen sources, including replies, forwarded-message timestamps, corrections and resolutions. Identify who said what, which customer/project they meant, why the discussion arose, and what actually changed. Keep distinct subjects separate even when they share a chat.\n' +
    'Provide the original changes and their relevant discussion context to system_one. Evaluate all frozen goals independently. Split long files by coherent discussion topics, not arbitrary lengths; preserve message IDs and attribution. Clearly distinguish new material from prior background.\n' +
    'Call system_one with {rawRef: "folio-raw:<toCommit>/<raw-path>", context: "original source changes and relevant context", goals: [{id, description}]}. Its matched result means probability >= 0.7. Lower probabilities do not create todos. When context is insufficient, read additional original material before judging again; do not repeat unchanged requests to seek a match.\n' +
    `Immediately save screening progress and goal matches to ${KNOWLEDGE_TODO_FILE}, including already screened raws with no matches. Consolidate matches into topic-based todos: each todo records the knowledge to curate, the specific subject, matched goals, supporting frozen message references (possibly from several raws), discussion context and intended outcome. Keep every match traceable to a todo or a documented no-change reason. One raw can contain unrelated topics; several raws can support the same topic.\n` +
    'A tool error is unresolved work, not a negative match. Correct a configuration/input issue or retry a transient issue; if it remains unresolved, preserve progress and report the failure without declaring screening complete.\n' +
    'Finish screening all frozen raw paths and save the complete todo list before writing Wiki content. Zero matches is a valid result.',
    `Phase 2 — curation:\n` +
    'Read wiki/_types.json and search the existing Wiki for knowledge relevant to the todos. Follow each target ObjectType\'s template. Content, Idea, and Question are available for the corresponding goals. Read only the existing pages needed for this work.\n' +
    'For each todo decide whether to create, update, combine related knowledge, or make no change. Prefer extending relevant existing pages and link genuinely related existing knowledge. Use stable, specific topics rather than daily collections of unrelated incidents. Several todos may contribute to one page. A mention of an entity does not require creating it; a goal match does not require a new page.\n' +
    'Content must preserve reusable facts, methods, rules, cases or a coherent argument. Retain useful steps, parameter names, code/request structures and examples; replace credentials with placeholders rather than removing the example. Routine alerts, status cards and requirement-created notifications warrant a page only when they contribute meaningful knowledge beyond the notification.\n' +
    'Idea must preserve an idea or opinion actually expressed in the source, with its proposer, motivation and scope. A registered requirement is not by itself an unfinished idea. Question must be explicitly raised or supported as unresolved by the discussion; check subsequent replies before retaining it. An alert with no diagnosis does not automatically justify a separate investigation-question page.\n' +
    'Write enough context in the body for a reader to understand it without opening citations: relevant date, participants, customer/project, trigger and constraints. Attribute personal views; distinguish proposals, confirmed decisions and observed facts. Preserve corrections and do not transfer one customer\'s contract, assumptions or constraints to another.\n' +
    'Missing information is not evidence that something is undecided, absent or broken. Do not turn empty owner fields into claims that responsibility or acceptance criteria are undefined. Include uncertainties only when the source actually raises them or they materially qualify a supported claim; omit empty template sections and generic lists of missing metrics. Do not invent facts or answers.\n' +
    `Update the file after processing each todo, checking it off and recording resulting Page links or the reason no Wiki change is needed. Mark the file completed only after every raw has been screened successfully and every todo is settled. All todos may result in no Wiki change.\n` +
    'Before declaring completion, review every authored page against its sources: subject and attribution are correct; later corrections/resolutions are reflected; each factual claim is supported; useful details remain; the page is independently understandable; its theme is stable; and it does not duplicate another page. Repair unsupported claims and unnecessary sections. Record review findings and their resolution in the progress file. Conclude with the knowledge created or updated and any unresolved work.',
    `Progress-file format:\nUse YAML frontmatter with fromCommit: ${JSON.stringify(input.fromCommit)}, toCommit: ${JSON.stringify(input.toCommit)}, and phase: screening | processing | completed. Use Markdown sections for screening progress and todos. Use - [ ] for pending work and - [x] for completed work; leave no unchecked work when phase is completed. Recover from this file and the existing Wiki draft, preserving the frozen goals above.`,
    'Wiki format and publication:\n' +
    'Create Markdown Pages with YAML frontmatter: stable id, title, objectType, parentId, icon, cover, favorite, trashed, createdAt, updatedAt, properties. Use wiki/<id>.md for new Pages, valid property keys and option IDs from wiki/_types.json, ISO timestamps, and booleans for favorite/trashed. icon is a string (empty when absent); cover is a URL string or null; parentId may be null.\n' +
    'Use [label](folio-page:<pageId>) for Page relationships and [source](folio-raw:<toCommit>/<raw-path>#<encoded-record-id>) for pinned raw citations. Label message sources with chat name, local date/time (and source time zone), speaker and a short description of the evidence. Cite the relevant proposal, clarification and correction together when the claim relies on the discussion; do not cite only an isolated sentence. Mail labels include subject, date and sender when available. Omit the fragment when no stable record ID exists. For a deleted raw still cite this Task\'s toCommit; Folio resolves its deletion diff and prior blob.\n' +
    `Edit only Wiki Page Markdown and ${KNOWLEDGE_TODO_FILE}. Do not edit raws, wiki/_types.json, or other workspace files. Do not delete or trash Pages, change existing Page IDs, or create placeholder milestones. Folio owns Git writes, validation, and Wiki publication; it returns validation issues to this Session for repair.`,
    `Routine execution instruction: ${input.instruction}`,
  ].join('\n\n')
}
