/** Real Electron regression: isolated Vault, native RPC, Git-backed saves, type editing and page menus. Run after pnpm build. */
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
const requireApp = createRequire(import.meta.url)
const entry = fileURLToPath(new URL('../out/main/index.js', import.meta.url))
const { _electron: electron, expect } = requireApp('@playwright/test')
const { mkdtemp, mkdir, readdir, readFile, realpath, rm } = requireApp('node:fs/promises')
const { tmpdir } = requireApp('node:os')
const { join } = requireApp('node:path')
;(async () => {
  const root = await realpath(await mkdtemp(join(tmpdir(), 'folio-wiki-e2e-')))
  const artifacts = await realpath(await mkdtemp(join(tmpdir(), 'folio-wiki-evidence-')))
  const wiki = join(root, 'Knowledge'); await mkdir(wiki)
  const app = await electron.launch({ executablePath: requireApp('electron'), args: [entry, '--user-data-dir=' + join(root, 'electron')], env: { ...process.env, FOLIO_CONFIG_DIR: join(root, 'config'), ELECTRON_RENDERER_URL: '' } })
  app.process().stderr.on('data', data => { const text = String(data); if (text.includes('Error')) console.log(text) })
  try {
    await app.evaluate(({ dialog }, folder) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [folder] }) }, wiki)
    const page = await app.firstWindow()
    const errors = []; const warnings = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); if (message.type() === 'warning') warnings.push(message.text()) })
    await page.getByRole('button', { name: /Open Vault|打开知识库/, exact: true }).click()
    await page.getByRole('heading', { name: /All pages|所有页面/, exact: true }).waitFor()
    await expect(page).toHaveTitle('Knowledge — Folio')
    await expect(page.locator('vite-error-overlay')).toHaveCount(0)
    console.log('Vault opened', await page.title(), page.url())
    await page.setViewportSize({ width: 1280, height: 900 })
    const primaryNavigation = page.getByRole('navigation', { name: /Workspace navigation|工作区导航/ })
    const wikiNavigation = page.getByRole('navigation', { name: /Wiki navigation|Wiki 导航/ })
    await expect(wikiNavigation).toBeVisible()
    const primaryBounds = await primaryNavigation.boundingBox()
    const wikiBounds = await wikiNavigation.boundingBox()
    if (!primaryBounds || !wikiBounds || wikiBounds.y < primaryBounds.y + primaryBounds.height || Math.abs(primaryBounds.x - wikiBounds.x) > 10) throw Error('Wiki navigation is not below the workspace menu')
    if (await page.getByRole('region').locator('nav, aside').count()) throw Error('Nested content sidebar remains')
    await page.screenshot({ animations: 'disabled', path: join(artifacts, 'empty.png') })

    await page.getByRole('button', { name: /New page|新建页面/, exact: true }).first().click()
    await page.getByRole('textbox', { name: /Page title|页面标题/, exact: true }).fill('Research workspace')
    await page.getByLabel(/Object type|对象类型/, { exact: true }).selectOption('project')
    await page.getByLabel('Status', { exact: true }).selectOption('In progress')
    await page.getByRole('button', { name: 'Markdown', exact: true }).click()
    await page.getByRole('textbox', { name: /Markdown source|Markdown 源码/ }).fill('# Research plan\n\nA **durable** knowledge page.\n\n- [ ] Read sources\n- [x] Create workspace\n\n| Topic | Status |\n| --- | --- |\n| Markdown | Ready |')
    await page.getByRole('button', { name: /Editor|编辑视图/, exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Research plan' })).toBeVisible()
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    const file = (await readdir(wiki)).find(name => name.endsWith('.md'))
    const content = await readFile(join(wiki, file), 'utf8')
    if (!content.includes('objectType: project') || !content.includes('status: In progress') || !content.includes('durable')) throw Error('File persistence mismatch')
    await page.screenshot({ animations: 'disabled', path: join(artifacts, 'page.png') })
    // Switching modules keeps the single editor mounted and lets the shared tree reopen it.
    await page.getByRole('button', { name: 'Markdown', exact: true }).click()
    await page.getByRole('textbox', { name: /Markdown source|Markdown 源码/ }).fill('# Research plan\n\nA **durable** knowledge page.\n\nDraft preserved across navigation.')
    await primaryNavigation.getByRole('button', { name: /Tasks|任务/, exact: true }).click()
    await expect(page.getByRole('textbox', { name: /Page title|页面标题/ })).toBeHidden()
    await wikiNavigation.getByRole('button', { name: /📁 Research workspace/ }).click()
    await expect(page.getByRole('textbox', { name: /Markdown source|Markdown 源码/ })).toHaveValue(/Draft preserved across navigation\./)
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    await page.getByRole('button', { name: /Editor|编辑视图/, exact: true }).click()
    await page.screenshot({ animations: 'disabled', path: join(artifacts, 'page.png') })

    await page.reload()
    await page.getByRole('button', { name: /📁 Research workspace/ }).first().click()
    await expect(page.getByRole('heading', { name: 'Research plan' })).toBeVisible()
    await expect(page.getByLabel('Status', { exact: true })).toHaveValue('In progress')
    await page.getByRole('button', { name: /Favorite page|收藏页面/ }).click()
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    await page.getByRole('button', { name: /^(Favorites|收藏)$/, exact: true }).click()
    await expect(page.getByRole('cell', { name: /Research workspace/ })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: join(artifacts, 'library.png') })
    await page.getByRole('button', { name: /Manage types|管理类型/, exact: true }).click()
    await page.getByRole('textbox', { name: /New type name|新类型名称/ }).fill('Book')
    await page.getByRole('button', { name: /New type|新建类型/, exact: true }).click()
    await page.getByRole('button', { name: /Add property|添加属性/ }).click()
    await page.getByRole('textbox', { name: /Property name 1|属性名称 1/ }).fill('Rating')
    await page.getByRole('combobox', { name: /Property kind 1|属性类型 1/ }).selectOption('number')
    await page.getByRole('button', { name: /Save types|保存类型/ }).click()
    await page.getByRole('textbox', { name: /New type name|新类型名称/ }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: /📄 Book/ }).click()
    await page.getByRole('heading', { name: 'Book', exact: true }).waitFor()
    await page.getByRole('button', { name: /New page|新建页面/, exact: true }).first().click()
    await page.getByRole('textbox', { name: /Page title|页面标题/ }).fill('A personal library')
    await page.getByRole('spinbutton', { name: 'Rating', exact: true }).fill('5')
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    await page.getByLabel(/Page menu|页面菜单/, { exact: true }).click()
    await page.getByRole('button', { name: /Duplicate|创建副本/, exact: true }).click()
    await expect(page.getByRole('textbox', { name: /Page title|页面标题/ })).toHaveValue(/A personal library.*(copy|副本)/)
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    await page.getByLabel(/Page menu|页面菜单/, { exact: true }).click()
    await page.getByRole('button', { name: /Move to trash|移到回收站/ }).click()
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    await page.getByLabel(/Page menu|页面菜单/, { exact: true }).click()
    await page.getByRole('button', { name: /Restore page|恢复页面/, exact: true }).click()
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    await page.getByLabel(/Page menu|页面菜单/, { exact: true }).click()
    await page.getByRole('button', { name: /^(Add subpage|添加子页面)$/, exact: true }).click()
    await page.getByRole('textbox', { name: /Page title|页面标题/ }).fill('Reading notes')
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    await expect(page.getByLabel(/Parent page|所属页面/, { exact: true })).not.toHaveValue('')
    await page.getByLabel(/Parent page|所属页面/, { exact: true }).selectOption('')
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    await expect(page.getByLabel(/Parent page|所属页面/, { exact: true })).toHaveValue('')
    const editor = page.locator('.wiki-prose')
    await editor.click()
    await editor.pressSequentially('/heading')
    await expect(page.getByRole('listbox', { name: /Slash commands|斜杠命令/ })).toBeVisible()
    await editor.press('Enter')
    await editor.pressSequentially('Reading list')
    await expect(page.getByRole('heading', { name: 'Reading list' })).toBeVisible()
    await editor.press('End'); await editor.press('Enter')
    await page.getByLabel(/Insert page link|插入页面链接/).selectOption({ label: 'Research workspace' })
    await expect(page.getByText(/^(Saved|已保存)$/)).toBeVisible({ timeout: 15000 })
    const exportedPath = join(root, 'export.md')
    await app.evaluate(({ session }, path) => {
      session.defaultSession.once('will-download', (_event, item) => item.setSavePath(path))
    }, exportedPath)
    await page.getByLabel(/Page menu|页面菜单/, { exact: true }).click()
    await page.getByRole('button', { name: /Export Markdown|导出 Markdown/, exact: true }).click()
    await expect.poll(() => readFile(exportedPath, 'utf8').catch(() => ''), { timeout: 10000 }).toContain('# Reading list')
    const exported = await readFile(exportedPath, 'utf8')
    if (exported.includes('"body":') || !exported.includes('"objectType":')) throw Error('Invalid Markdown export')
    await page.getByRole('link', { name: 'Research workspace', exact: true }).click({ modifiers: [process.platform === 'darwin' ? 'Meta' : 'Control'] })
    await expect(page.getByRole('textbox', { name: /Page title|页面标题/ })).toHaveValue('Research workspace')
    await page.setViewportSize({ width: 760, height: 780 })
    await page.screenshot({ animations: 'disabled', path: join(artifacts, 'narrow.png') })
    await page.getByRole('button', { name: 'Toggle Sidebar', exact: true }).click()
    await expect(wikiNavigation).toBeVisible()
    await expect(page.locator('[data-mobile=true]')).toHaveCSS('opacity', '1')
    await page.screenshot({ animations: 'disabled', path: join(artifacts, 'narrow-navigation.png') })
    await wikiNavigation.getByRole('button', { name: /📁 Research workspace/ }).click()
    await expect(wikiNavigation).toBeHidden()
    await expect(page.getByRole('textbox', { name: /Page title|页面标题/ })).toHaveValue('Research workspace')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('button', { name: 'Toggle Sidebar', exact: true }).click()
    await expect(wikiNavigation).toBeVisible()
    await wikiNavigation.getByRole('button', { name: /All pages|所有页面/, exact: true }).click()
    await expect(wikiNavigation).toBeHidden()
    await page.screenshot({ animations: 'disabled', path: join(artifacts, 'mobile.png') })

    const overflowing = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
    if (overflowing) throw Error('Narrow viewport overflows')
    console.log(JSON.stringify({ artifacts, persisted: true, reopened: true, favorite: true, types: true, duplicate: true, trashRestore: true, subpage: true, move: true, export: true, slashCommands: true, pageLinks: true, unifiedSidebar: true, crossSectionDraft: true, mobileNavigation: true, narrow: true, warnings, errors }))
    if (errors.length || warnings.length) throw Error('Renderer errors or warnings')
  } catch (error) { for (const page of app.windows()) { console.log((await page.locator('body').innerText()).slice(0, 6000)); await page.screenshot({ animations: 'disabled', path: join(artifacts, 'failure.png') }) }; throw error } finally { await app.close(); await rm(root, { recursive: true, force: true }) }
})().catch(error => { console.error(error); process.exitCode = 1 })
